"""Alembic environment, async and SQLite-aware.

The URL comes from core.users rather than alembic.ini so there is one source of
truth for which file is the database. render_as_batch is what makes an
autogenerated ALTER work at all: SQLite cannot alter a column, so Alembic has to
rebuild the table instead.
"""

import asyncio

from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine

from core.users import DATABASE_URL, Base

target_metadata = Base.metadata


def _run(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_online() -> None:
    engine = create_async_engine(DATABASE_URL)
    async with engine.connect() as connection:
        await connection.run_sync(_run)
        await connection.commit()
    await engine.dispose()


if context.is_offline_mode():
    context.configure(url=DATABASE_URL, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()
else:
    asyncio.run(run_online())
